name: Go Release

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  actions: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all tags are fetched

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Debug logs
        run: |
          git fetch --tags
          git tag
          git describe --tags --abbrev=0 || echo "No tags found"

      - name: Get current tag
        id: get_version
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "current_tag=$TAG" >> $GITHUB_ENV

      - name: Calculate next tag
        id: calculate_tag
        run: |
          CURRENT_TAG="${{ env.current_tag }}"
          echo "Current Tag: $CURRENT_TAG"

          if [[ "$CURRENT_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            BASE_VERSION=$(echo "$CURRENT_TAG" | cut -d 'v' -f 2)
            MAJOR=$(echo "$BASE_VERSION" | cut -d '.' -f 1)
            MINOR=$(echo "$BASE_VERSION" | cut -d '.' -f 2)
            PATCH=$(echo "$BASE_VERSION" | cut -d '.' -f 3)
            NEXT_TAG="v$MAJOR.$MINOR.$((PATCH + 1))"
          else
            NEXT_TAG="v0.0.1"
          fi

          while git rev-parse "$NEXT_TAG" >/dev/null 2>&1; do
            PATCH=$(echo "$NEXT_TAG" | cut -d '.' -f 3)
            NEXT_TAG="v$MAJOR.$MINOR.$((PATCH + 1))"
          done

          echo "Final Next Tag: $NEXT_TAG"
          echo "tag=$NEXT_TAG" >> $GITHUB_ENV

      - name: Build for all platforms
        id: build
        run: |
          mkdir -p build
          platforms=("aix/ppc64" "android/386" "android/amd64" "android/arm" "android/arm64" "darwin/amd64" "darwin/arm64" "dragonfly/amd64" "freebsd/386" "freebsd/amd64" "freebsd/arm" "freebsd/arm64" "freebsd/riscv64" "illumos/amd64" "ios/amd64" "ios/arm64" "js/wasm" "linux/386" "linux/amd64" "linux/arm" "linux/arm64" "linux/loong64" "linux/mips" "linux/mips64" "linux/mips64le" "linux/mipsle" "linux/ppc64" "linux/ppc64le" "linux/riscv64" "linux/s390x" "netbsd/386" "netbsd/amd64" "netbsd/arm" "netbsd/arm64" "openbsd/386" "openbsd/amd64" "openbsd/arm" "openbsd/arm64" "openbsd/ppc64" "openbsd/riscv64" "plan9/386" "plan9/amd64" "plan9/arm" "solaris/amd64" "wasip1/wasm" "windows/386" "windows/amd64" "windows/arm" "windows/arm64")
          for platform in "${platforms[@]}"; do
            GOOS=${platform%/*} 
            GOARCH=${platform#*/}
            output_name=build/${GITHUB_REPOSITORY##*/}_${GOOS}_${GOARCH}
            if [[ "$GOOS" == "windows" ]]; then
              output_name+='.exe'
            fi
            env GOOS=$GOOS GOARCH=$GOARCH go build -trimpath -ldflags="-s -w -buildid= -extldflags='-fno-PIC'" -gcflags="all=-l -B -trimpath=" -o $output_name -v || echo "Failed to build for $platform"
          done

      - name: Create or Update Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag }}
          name: Release ${{ env.tag }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            build/*